version: '3.3'

services: 
  gunicorn:
    build: .

    volumes: 
      - static_files:/usr/src/app/alirezaies/static/:z
      - gunicorn_sock:/tmp/:z

    environment: 
      DEBUG: 'False'
      SECRET_KEY: '%&g@zvby_w+1e1p07c2&by@ckai@!at-xk9c%nvht=t-0fwpxy'
      RECAPTCHA_PUBLIC_KEY: 'MyRecaptchaKey123'
      RECAPTCHA_PRIVATE_KEY: 'MyRecaptchaPrivateKey456'
  
  nginx:
    image: nginx:1.17.9
    ports:
      - 8080:80

    volumes: 
      - static_files:/usr/share/nginx/html/static/:z
      - ./nginx.conf:/etc/nginx/nginx.conf:z
      - gunicorn_sock:/tmp/:z


volumes: 
  static_files:
  gunicorn_sock: