version: '3.3'

services: 
  gunicorn:
    build: .

    volumes: 
      - gunicorn_socket:/tmp/:z
      - static_files:/usr/src/app/alirezaies/static:z

    environment: 
      DEBUG: 'False'
      SECRET_KEY: '%&g@zvby_w+1e1p07c2&by@ckai@!at-xk9c%nvht=t-0fwpxy'
      WEBSITE_DOMAIN: 'sadegh.org'
  
  nginx:
    image: nginx:1.17.9
    ports:
      - 8080:80

    volumes: 
      - gunicorn_socket:/tmp/:z
      - static_files:/usr/share/nginx/html/static/:z
      - ./nginx.conf:/etc/nginx/nginx.conf:z


volumes: 
  gunicorn_socket:
  static_files: